In [8]:
import pandas as pd
from arabica import arabica_freq

In [9]:
data = pd.read_csv('headlines.csv')

In [10]:
head = data.head(7)
styled_head = head.style.set_table_styles(
    [{'selector': 'th', 'props': [('text-align', 'left'), ('font-size', '12pt')]}, #colums
     {'selector': 'td', 'props': [('text-align', 'left'), ('font-size', '10pt')]}] # text
)
display(styled_head)

In [23]:
result = arabica_freq(text = data['headline'], # Text
             time = data['date'],              # Time
             time_freq = 'M',                  # Aggregation period
             max_words = 4,                    # Max number for n-grams to be displayed
             date_format = 'us',               # Use US-style date format to parse dates
             stopwords = ['english'],          # Language for stop words
             stopwords_ext = None,             # Remove extended list of English stopwords
             skip = ['Jan','Feb','Dr',         # Remove additional strings
                     "—","Says"],
             lower_case = True,                # Lowercase text before cleaning and frequency analysis
             numbers = True)                   # Remove all digits

In [24]:
styled_head = result.style.set_table_styles(
    [{'selector': 'th', 'props': [('text-align', 'left'), ('font-size', '12pt')]}, #colums
     {'selector': 'td', 'props': [('text-align', 'left'), ('font-size', '10pt')]}] # text
)
display(styled_head)

In [31]:
arabica_freq(text = data['headline'],    # Text
             time = data['date'],        # Time
             time_freq = 'ungroup',      # Aggregation period
             max_words = 10,             # Max number for n-grams to be displayed
             date_format = 'us',         # Use US-style date format to parse dates
             stopwords = ["English"],    # Language for stop words
             stopwords_ext = None,       # Remove extended list of English stopwords
             skip = ['Jan','Feb','Dr',   # Remove additional strings
                      "—","Says"],
             lower_case = False,         # Lowercase text before cleaning and frequency analysis
             numbers = True)             # Remove all digits

c:\Users\xpetr\.conda\envs\arabica_testing\lib\site-packages\arabica\arabica_freq.py:153: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
c:\Users\xpetr\.conda\envs\arabica_testing\lib\site-packages\arabica\arabica_freq.py:154: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
c:\Users\xpetr\.conda\envs\arabica_testing\lib\site-packages\arabica\arabica_freq.py:163: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
c:\Users\xpetr\.conda\envs\arabica_testing\lib\site-packages\arabica\arabica_freq.py:164: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
c:\Users\xpetr\.conda\envs\arabica_testing\lib\site-packages\arabica\arabica_freq.py:166: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
c:\Users\xpetr\.conda\envs\arabica_testing\lib\site-packages\arabica\arabica_freq.py:167: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
c:\Users\xpetr\.conda\envs\arabica_testing\lib\site-packages\arabica\arabica_freq.py:184: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
c:\Users\xpetr\.conda\envs\arabica_testing\lib\site-packages\arabica\arabica_freq.py:185: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
c:\Users\xpetr\.conda\envs\arabica_testing\lib\site-packages\arabica\arabica_freq.py:196: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
c:\Users\xpetr\.conda\envs\arabica_testing\lib\site-packages\arabica\arabica_freq.py:201: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
c:\Users\xpetr\.conda\envs\arabica_testing\lib\site-packages\arabica\arabica_freq.py:202: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
c:\Users\xpetr\.conda\envs\arabica_testing\lib\site-packages\arabica\arabica_freq.py:204: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
c:\Users\xpetr\.conda\envs\arabica_testing\lib\site-packages\arabica\arabica_freq.py:205: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
c:\Users\xpetr\.conda\envs\arabica_testing\lib\site-packages\arabica\arabica_freq.py:222: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
c:\Users\xpetr\.conda\envs\arabica_testing\lib\site-packages\arabica\arabica_freq.py:223: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
c:\Users\xpetr\.conda\envs\arabica_testing\lib\site-packages\arabica\arabica_freq.py:233: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.

,unigram,unigram_freq,bigram,bigram_freq,trigram,trigram_freq
0,coronavirus,147,"Donald,Trump",49,"President,Donald,Trump",20
1,Trump,117,"Joe,Biden",40,"Gov,Tony,Evers",8
2,people,100,"photo,shows",34,"New,York,City",7
3,COVID,93,"President,Donald",25,"shows,Joe,Biden",7
4,shows,73,"Nancy,Pelosi",24,"Nancy,Pelosi,said",5
5,President,63,"Bernie,Sanders",23,"President,Donald,Trumps",5
6,US,63,"United,States",22,"World,Health,Organization",5
7,Donald,55,"New,York",21,"rockets,launched,toward",4
8,Biden,49,"President,Trump",15,"Donald,Trump,tweeted",4
9,photo,49,"Barack,Obama",13,"Black,Lives,Matter",4

In [32]:
styled_head = result.style.set_table_styles(
    [{'selector': 'th', 'props': [('text-align', 'left'), ('font-size', '12pt')]}, #colums
     {'selector': 'td', 'props': [('text-align', 'left'), ('font-size', '10pt')]}] # text
)
display(styled_head)

In [ ]:
arabica_freq(text = data['headline'],           # Text
             time = data['date'],               # Time
             time_freq = 'ungroup',             # Aggregation period
             max_words = 10,                    # Max number for n-grams to be displayed
             date_format = 'us',                # Use US-style date format to parse dates
             stopwords = ["English","German",   # Languages for stop words
                          "French"],            
             stopwords_ext = None,              # Remove extended list of English stopwords
             skip = ['Jan','Feb','Dr',          # Remove additional strings
                      "—","Says"],
             lower_case = False,                # Lowercase text before cleaning and frequency analysis
             numbers = True)                    # Remove all digits

c:\Users\xpetr\.conda\envs\arabica_testing\lib\site-packages\arabica\arabica_freq.py:153: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
c:\Users\xpetr\.conda\envs\arabica_testing\lib\site-packages\arabica\arabica_freq.py:154: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
c:\Users\xpetr\.conda\envs\arabica_testing\lib\site-packages\arabica\arabica_freq.py:163: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
c:\Users\xpetr\.conda\envs\arabica_testing\lib\site-packages\arabica\arabica_freq.py:164: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
c:\Users\xpetr\.conda\envs\arabica_testing\lib\site-packages\arabica\arabica_freq.py:166: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
c:\Users\xpetr\.conda\envs\arabica_testing\lib\site-packages\arabica\arabica_freq.py:167: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
c:\Users\xpetr\.conda\envs\arabica_testing\lib\site-packages\arabica\arabica_freq.py:184: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
c:\Users\xpetr\.conda\envs\arabica_testing\lib\site-packages\arabica\arabica_freq.py:185: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
c:\Users\xpetr\.conda\envs\arabica_testing\lib\site-packages\arabica\arabica_freq.py:196: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
c:\Users\xpetr\.conda\envs\arabica_testing\lib\site-packages\arabica\arabica_freq.py:201: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
c:\Users\xpetr\.conda\envs\arabica_testing\lib\site-packages\arabica\arabica_freq.py:202: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
c:\Users\xpetr\.conda\envs\arabica_testing\lib\site-packages\arabica\arabica_freq.py:204: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
c:\Users\xpetr\.conda\envs\arabica_testing\lib\site-packages\arabica\arabica_freq.py:205: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
c:\Users\xpetr\.conda\envs\arabica_testing\lib\site-packages\arabica\arabica_freq.py:222: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
c:\Users\xpetr\.conda\envs\arabica_testing\lib\site-packages\arabica\arabica_freq.py:223: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
c:\Users\xpetr\.conda\envs\arabica_testing\lib\site-packages\arabica\arabica_freq.py:233: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.

,unigram,unigram_freq,bigram,bigram_freq,trigram,trigram_freq
0,Says,405,"Dald,Trump",49,"Says,photo,shows",21
1,coravirus,147,"Joe,Biden",40,"President,Dald,Trump",20
2,Trump,117,"photo,shows",34,"Says,Joe,Biden",15
3,people,100,"Says,photo",26,"Says,President,Dald",14
4,COVID,93,"President,Dald",25,"Says,Nancy,Pelosi",10
5,shows,73,"Nancy,Pelosi",24,"Says,video,shows",10
6,US,63,"Bernie,Sanders",23,"Says,Dald,Trump",9
7,President,63,"United,States",22,"Gov,Ty,Evers",8
8,Dald,55,"New,York",21,"Says,Bernie,Sanders",7
9,Biden,49,"Says,President",19,"shows,Joe,Biden",7